version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
        - MYSQL_DATABASE='db_devops'
        - MYSQL_USER='root'
        - MYSQL_PASSWORD='12345678'
        - MYSQL_ROOT_PASSWORD='12345678'
        - MYSQL_HOST=''
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  web:
    build: .
    command: python3 web_app.py
    volumes:
      - .:/app
    ports:
      - "5001:5001"
    depends_on:
      - db
  rest_app:
    build: .
    command: python3 rest_app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

